In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)


2.20.0


In [6]:
x = np.array([200, 17])
print("Shape of x = ",x.shape)
q = np.array([[200], [17]])
print("Shape of q = ",q.shape)


Shape of x =  (2,)
Shape of q =  (2, 1)


In [7]:
def sigmoid(z):
   """
   Calculate the sigmoid function of a z score. Mostly used for logistic regression
   """
   return 1 / (1 + np.exp(-z))

In [8]:
w1_1 = np.array([1,2])
b1_1 = np.array([-1])
z1_1 = np.dot(w1_1,x) + b1_1
a1_1 = sigmoid(z1_1)
a1_1

array([1.])

In [9]:
w1_2 = np.array([-3,4])
b1_2 = np.array([1])
z1_2 = np.dot(w1_2,x) + b1_2
a1_2 = sigmoid(z1_2)
a1_2

array([2.45261912e-231])

In [10]:
w1_3 = np.array([5,-6])
b1_3 = np.array([2])
z1_3 = np.dot(w1_3,x) + b1_3
a1_3 = sigmoid(z1_3)
a1_3

array([1.])

In [12]:
a1 = np.array([a1_1, a1_2, a1_3])
a1

array([[1.00000000e+000],
       [2.45261912e-231],
       [1.00000000e+000]])

In [13]:
w2_1 = np.array([-7,8,9])
b2_1 = np.array([3])
z2_1 = np.dot(w2_1,a1) + b2_1
a2_1 = sigmoid(z2_1)
a2_1

array([0.99330715])

In [ ]:
def Dense(a, W, b):
   """
   Dense is an implementation of a dense layer of a Neural Network(NN) construction
   """
   units = W.shape[1]
   a_out = np.zeros(units)
   for j in range(units):
      w = W[:, j]
      z = np.dot(w, a) + b[j]
      a_out[j] = sigmoid(z)
   return a_out


In [ ]:
def sequential(x):
   """
   sequential is the implementation of the forward propagation
   """
   a1 = Dense(x, W1,b1)
   a2 = Dense(a1, W2,b2)
   a3 = Dense(a2, W3,b3)
   a4 = Dense(a3, W4,b4)
   f_x = a4
   return f_x


In [ ]:
def vectorisedForwardProp(a_in, W, b):
   z = np.matmul(a_in, W) + b
   a_out = sigmoid(z)
   return a_out